# Generated by Django 2.2 on 2020-07-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajax_django_posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdata',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
