# Generated by Django 2.2 on 2020-07-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajax_django_posts', '0004_auto_20200706_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdata',
            name='ur',
            field=models.CharField(blank=True, default='<django.db.models.fields.CharField>', max_length=100),
        ),
    ]
