# Generated by Django 2.2 on 2020-07-06 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ajax_django_posts', '0006_auto_20200706_2306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postdata',
            old_name='ur',
            new_name='url',
        ),
    ]
