# Generated by Django 2.2 on 2020-07-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajax_django_posts', '0007_auto_20200706_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdata',
            name='url',
            field=models.CharField(default=models.CharField(max_length=100), max_length=100),
        ),
    ]
