# Generated by Django 2.2 on 2020-07-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajax_django_posts', '0008_auto_20200706_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdata',
            name='url',
            field=models.CharField(default='<django.db.models.fields.CharField>', max_length=100),
        ),
    ]
