# Generated by Django 3.0.8 on 2020-07-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajax_django_posts', '0010_auto_20200707_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdata',
            name='url',
            field=models.CharField(default='s', max_length=200),
        ),
    ]
