# Generated by Django 3.0.8 on 2020-07-07 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ajax_django_posts', '0011_auto_20200707_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postdata',
            old_name='name',
            new_name='short_name',
        ),
    ]
