# Generated by Django 3.0.8 on 2020-07-07 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ajax_django_posts', '0012_auto_20200707_1729'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Postdata',
        ),
    ]
