# Generated by Django 3.0.8 on 2020-07-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ajax_django_posts', '0013_delete_postdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=200)),
                ('url', models.CharField(default='s', max_length=200)),
            ],
        ),
    ]
