# Generated by Django 3.0.8 on 2020-07-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajax_django_posts', '0015_auto_20200707_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdata',
            name='heading',
            field=models.CharField(max_length=200),
        ),
    ]
