# Generated by Django 3.0.8 on 2020-07-09 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ajax_django_posts', '0017_auto_20200708_1501'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Postdata',
        ),
    ]
