# Generated by Django 3.0.8 on 2020-07-09 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ajax_django_posts', '0019_postdata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Postdata',
            new_name='DjangoAjaxPosts',
        ),
    ]
