# Generated by Django 3.0.8 on 2020-07-11 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ajax_django_posts', '0022_auto_20200711_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='djangoajaxposts',
            name='description',
        ),
    ]
