# Generated by Django 3.0.8 on 2020-07-11 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ajax_django_posts', '0026_djangoajaxposts_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='djangoajaxposts',
            name='description',
        ),
    ]
