# Generated by Django 3.0.8 on 2020-07-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_how_to', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='djangohowtopost',
            name='url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
