# Generated by Django 3.0.8 on 2020-07-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_how_to', '0002_djangohowtopost_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='djangohowtopost',
            name='description',
            field=models.TextField(default='Coming Soon !'),
        ),
    ]
