# Generated by Django 3.0.8 on 2020-07-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_how_to', '0005_remove_djangohowtopost_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='djangohowtopost',
            name='description',
            field=models.TextField(default='Here description will be place !'),
        ),
    ]
