# Generated by Django 3.0.8 on 2020-07-11 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_how_to', '0006_djangohowtopost_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='djangohowtopost',
            name='description',
        ),
    ]
