# Generated by Django 3.0.8 on 2020-07-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_how_to', '0007_remove_djangohowtopost_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='djangohowtopost',
            name='description',
            field=models.TextField(default='Here description will be placed !'),
        ),
    ]
